Add CEU table in events
tendenci/tendenci pull request #1160
Opened 2023-03-03 21:45 UTC by shandy-bixly

2023-06-12 21:53 UTC, jennyq requested changes
1. At admin backend, please hide "Continuing Education Unit Categories" if the setting "Use Credits" is not turned on to not confuse sites that don't use CEUs?
```
    if get_setting('module', 'events', 'use_credits'):
            admin.site.register(CEUCategory, CEUCategoryAdmin)
```
2. Under the Credits tab on event edit, if there is no CEU categories set up yet, instead of leaving it as blank,  maybe add a link for superusers to add CEU categories?
3. IntegrityError when deleting a CEU sub-category at admin  at /admin/events/ceucategory/4/change/ (when the sub-category is being referenced by an event)
`update or delete on table "events_ceucategory" violates foreign key constraint "events_eventcredit_ceu_subcategory_id_e906b5d5_fk_events_ce" on table "events_eventcredit"
DETAIL:  Key (id)=(6) is still referenced from table "events_eventcredit".`
4. Checked with Nicole, the number of credits (the `credit_count` field in EventCredit) needs to be a decimal (for example, 0.5), not an integer. 
5. Would it be possible to allow text wrapping for the name of the sub-categories instead of being cut off on the credits edit? See the attached image where "Business Management and Organization" and "IRS-CE - IRS Continuing Education" are being cut off. 
![image](https://github.com/tendenci/tendenci/assets/106448/411f7a0d-2a1a-4183-b7f9-629b25ca4583)

2023-06-12 21:55 UTC, jennyq commented
Hi Shandy,

Thanks for all you do! Just letting you know that, due to the potential conflicting migrations in events, we'll have to merge the PR "Add event cancellation fields #1159" first before merging this one. Likewise, the next PR will be merged after this one.

2023-07-05 16:15 UTC, shandy-bixly commented
> 1. At admin backend, please hide "Continuing Education Unit Categories" if the setting "Use Credits" is not turned on to not confuse sites that don't use CEUs?
> 
> ```
>     if get_setting('module', 'events', 'use_credits'):
>             admin.site.register(CEUCategory, CEUCategoryAdmin)
> ```
> 
> 2. Under the Credits tab on event edit, if there is no CEU categories set up yet, instead of leaving it as blank,  maybe add a link for superusers to add CEU categories?
> 3. IntegrityError when deleting a CEU sub-category at admin  at /admin/events/ceucategory/4/change/ (when the sub-category is being referenced by an event)
>    `update or delete on table "events_ceucategory" violates foreign key constraint "events_eventcredit_ceu_subcategory_id_e906b5d5_fk_events_ce" on table "events_eventcredit" DETAIL:  Key (id)=(6) is still referenced from table "events_eventcredit".`
> 4. Checked with Nicole, the number of credits (the `credit_count` field in EventCredit) needs to be a decimal (for example, 0.5), not an integer.
> 5. Would it be possible to allow text wrapping for the name of the sub-categories instead of being cut off on the credits edit? See the attached image where "Business Management and Organization" and "IRS-CE - IRS Continuing Education" are being cut off.
>    ![image](https://user-images.githubusercontent.com/106448/245580413-411f7a0d-2a1a-4183-b7f9-629b25ca4583.png)

Will take a look!

2023-07-08 22:53 UTC, jennyq approved these changes

2023-07-09 02:04 UTC, merged